### PR TITLE
Add orientation timestamp offset

### PR DESCRIPTION
**Pull request by aftersomemath**

### CODE REVIEW

**Comment by amiller27** [comment]
This is tested, right?

**Comment by aftersomemath** [comment]
Yes

**Comment by amiller27** [comment]
So I'm thinking we shouldn't merge this until the Optical Flow PR is also ready

**Comment by aftersomemath** [comment]
I agree. No need to risk it getting mixed up on the drone.

**Review by amiller27 — APPROVED** [review]

**Pull request merged**
