### PR TITLE
Removed unnecessary dependencies

### PR DESCRIPTION
**Pull request by amiller27**

### CODE REVIEW

**Comment by aftersomemath** [comment]
What is the purpose of this? They will be a dependency in the future, why not clone them now to get the workspace started. Else it will also not be readily apparent where things go when someones working out of a workspace.

**Comment by amiller27** [comment]
@aftersomemath Because packages are shippable units.  A package shouldn't depend on every part of iarc7, it only depends on the things it needs.  Most of those things will never be dependencies of this package, and the ones that will should be marked as dependencies when they actually become dependencies.

**Comment by amiller27** [comment]
This doesn't affect how developers construct their workspaces, they still do that from the iarc7_common/main.rosinstall file.  This one is for dependencies of this package only.  Right now it's only used by the build testing on Travis, but in principle it would be used by anyone who wants to use this package and only this package.

**Review by aftersomemath — APPROVED** [review]
I did not see that this is for fc_comms and assumed it was for the common workspace setup script. I assume this is for travis.

**Pull request merged**
