### PR TITLE
Remove flight controller mode switching

### PR DESCRIPTION
**Pull request by aftersomemath**
Remove flight controller mode switching as it is no longer needed.

Do not merge until Evan's switch checking PR's are done.

@MiscM This branch should be on the drone when you are performing your testing

### CODE REVIEW

**Comment by aftersomemath** [comment]
Ready

**Review by amiller27 — APPROVED** [review]

**Review by asaba96 — COMMENTED** [review]
I see no issues with this. @amiller27 might have additional comments.

**Comment by asaba96** [comment]
This can't be merged until motion is merged, right?

**Comment by aftersomemath** [comment]
Correct

**Pull request merged**
